train_size: 45000

width: 32
dropout: 0.0

batch_size: 128

lr: 0.05
momentum: 0.9
weight_decay: 0.0005

epochs: 30
patience: 10

seed: 42

augmentation: false
scheduler: false
early_stopping: false

run_name: wd5e-4_w32_n45000_s42